
# define prune ratios for your network
prune_ratios:

  # features.models.0.models.0.weight:
  #   0.99
  # features.models.0.models.0.taskOp.multiclass.weight:
  #   0.99
  # features.models.0.models.0.taskOp.binary.weight:
  #   0.99
  # features.models.0.models.0.dsOp.multiclass.0.weight:
  #   0.99
  # features.models.0.models.0.dsOp.binary.0.weight:
  #   0.99
  features.models.1.conv.models.0.weight:
    0.99
  features.models.1.conv.models.0.taskOp.multiclass.weight:
    0.99
  features.models.1.conv.models.0.taskOp.binary.weight:
    0.999
  features.models.1.conv.models.3.weight:
    0.99
  features.models.1.conv.models.3.taskOp.multiclass.weight:
    0.99
  features.models.1.conv.models.3.taskOp.binary.weight:
    0.999
  features.models.1.conv.models.3.dsOp.multiclass.0.weight:
    0.99
  features.models.1.conv.models.3.dsOp.binary.0.weight:
    0.999
  features.models.2.conv.models.0.weight:
    0.99
  features.models.2.conv.models.0.taskOp.multiclass.weight:
    0.99
  features.models.2.conv.models.0.taskOp.binary.weight:
    0.999
  features.models.2.conv.models.0.dsOp.multiclass.0.weight:
    0.99
  features.models.2.conv.models.0.dsOp.binary.0.weight:
    0.999
  features.models.2.conv.models.3.weight:
    0.99
  features.models.2.conv.models.3.taskOp.multiclass.weight:
    0.99
  features.models.2.conv.models.3.taskOp.binary.weight:
    0.999
  features.models.2.conv.models.6.weight:
    0.99
  features.models.2.conv.models.6.taskOp.multiclass.weight:
    0.99
  features.models.2.conv.models.6.taskOp.binary.weight:
    0.999
  features.models.2.conv.models.6.dsOp.multiclass.0.weight:
    0.99
  features.models.2.conv.models.6.dsOp.binary.0.weight:
    0.999
  features.models.3.conv.models.0.weight:
    0.99
  features.models.3.conv.models.0.taskOp.multiclass.weight:
    0.99
  features.models.3.conv.models.0.taskOp.binary.weight:
    0.999
  features.models.3.conv.models.0.dsOp.multiclass.0.weight:
    0.99
  features.models.3.conv.models.0.dsOp.binary.0.weight:
    0.999
  features.models.3.conv.models.3.weight:
    0.99
  features.models.3.conv.models.3.taskOp.multiclass.weight:
    0.99
  features.models.3.conv.models.3.taskOp.binary.weight:
    0.999
  features.models.3.conv.models.6.weight:
    0.99
  features.models.3.conv.models.6.taskOp.multiclass.weight:
    0.99
  features.models.3.conv.models.6.taskOp.binary.weight:
    0.999
  features.models.3.conv.models.6.dsOp.multiclass.0.weight:
    0.99
  features.models.3.conv.models.6.dsOp.binary.0.weight:
    0.999
  features.models.4.conv.models.0.weight:
    0.99
  features.models.4.conv.models.0.taskOp.multiclass.weight:
    0.99
  features.models.4.conv.models.0.taskOp.binary.weight:
    0.999
  features.models.4.conv.models.0.dsOp.multiclass.0.weight:
    0.99
  features.models.4.conv.models.0.dsOp.binary.0.weight:
    0.999
  features.models.4.conv.models.3.weight:
    0.99
  features.models.4.conv.models.3.taskOp.multiclass.weight:
    0.99
  features.models.4.conv.models.3.taskOp.binary.weight:
    0.999
  features.models.4.conv.models.3.dsOp.multiclass.0.weight:
    0.99
  features.models.4.conv.models.3.dsOp.binary.0.weight:
    0.999
  features.models.4.conv.models.6.weight:
    0.99
  features.models.4.conv.models.6.taskOp.multiclass.weight:
    0.99
  features.models.4.conv.models.6.taskOp.binary.weight:
    0.999
  features.models.4.conv.models.6.dsOp.multiclass.0.weight:
    0.99
  features.models.4.conv.models.6.dsOp.binary.0.weight:
    0.999
  features.models.5.conv.models.0.weight:
    0.99
  features.models.5.conv.models.0.taskOp.multiclass.weight:
    0.99
  features.models.5.conv.models.0.taskOp.binary.weight:
    0.999
  features.models.5.conv.models.0.dsOp.multiclass.0.weight:
    0.99
  features.models.5.conv.models.0.dsOp.binary.0.weight:
    0.999
  features.models.5.conv.models.3.weight:
    0.99
  features.models.5.conv.models.3.taskOp.multiclass.weight:
    0.99
  features.models.5.conv.models.3.taskOp.binary.weight:
    0.999
  features.models.5.conv.models.6.weight:
    0.99
  features.models.5.conv.models.6.taskOp.multiclass.weight:
    0.99
  features.models.5.conv.models.6.taskOp.binary.weight:
    0.999
  features.models.5.conv.models.6.dsOp.multiclass.0.weight:
    0.99
  features.models.5.conv.models.6.dsOp.binary.0.weight:
    0.999
  features.models.6.conv.models.0.weight:
    0.99
  features.models.6.conv.models.0.taskOp.multiclass.weight:
    0.99
  features.models.6.conv.models.0.taskOp.binary.weight:
    0.999
  features.models.6.conv.models.0.dsOp.multiclass.0.weight:
    0.99
  features.models.6.conv.models.0.dsOp.binary.0.weight:
    0.999
  features.models.6.conv.models.3.weight:
    0.99
  features.models.6.conv.models.3.taskOp.multiclass.weight:
    0.99
  features.models.6.conv.models.3.taskOp.binary.weight:
    0.999
  features.models.6.conv.models.6.weight:
    0.99
  features.models.6.conv.models.6.taskOp.multiclass.weight:
    0.99
  features.models.6.conv.models.6.taskOp.binary.weight:
    0.999
  features.models.6.conv.models.6.dsOp.multiclass.0.weight:
    0.99
  features.models.6.conv.models.6.dsOp.binary.0.weight:
    0.999
  features.models.7.conv.models.0.weight:
    0.99
  features.models.7.conv.models.0.taskOp.multiclass.weight:
    0.99
  features.models.7.conv.models.0.taskOp.binary.weight:
    0.999
  features.models.7.conv.models.0.dsOp.multiclass.0.weight:
    0.99
  features.models.7.conv.models.0.dsOp.binary.0.weight:
    0.999
  features.models.7.conv.models.3.weight:
    0.99
  features.models.7.conv.models.3.taskOp.multiclass.weight:
    0.99
  features.models.7.conv.models.3.taskOp.binary.weight:
    0.999
  features.models.7.conv.models.3.dsOp.multiclass.0.weight:
    0.99
  features.models.7.conv.models.3.dsOp.binary.0.weight:
    0.999
  features.models.7.conv.models.6.weight:
    0.99
  features.models.7.conv.models.6.taskOp.multiclass.weight:
    0.99
  features.models.7.conv.models.6.taskOp.binary.weight:
    0.999
  features.models.7.conv.models.6.dsOp.multiclass.0.weight:
    0.99
  features.models.7.conv.models.6.dsOp.binary.0.weight:
    0.999
  features.models.8.conv.models.0.weight:
    0.99
  features.models.8.conv.models.0.taskOp.multiclass.weight:
    0.99
  features.models.8.conv.models.0.taskOp.binary.weight:
    0.999
  features.models.8.conv.models.0.dsOp.multiclass.0.weight:
    0.99
  features.models.8.conv.models.0.dsOp.binary.0.weight:
    0.999
  features.models.8.conv.models.3.weight:
    0.99
  features.models.8.conv.models.3.taskOp.multiclass.weight:
    0.99
  features.models.8.conv.models.3.taskOp.binary.weight:
    0.999
  features.models.8.conv.models.6.weight:
    0.99
  features.models.8.conv.models.6.taskOp.multiclass.weight:
    0.99
  features.models.8.conv.models.6.taskOp.binary.weight:
    0.999
  features.models.8.conv.models.6.dsOp.multiclass.0.weight:
    0.99
  features.models.8.conv.models.6.dsOp.binary.0.weight:
    0.999
  features.models.9.conv.models.0.weight:
    0.99
  features.models.9.conv.models.0.taskOp.multiclass.weight:
    0.99
  features.models.9.conv.models.0.taskOp.binary.weight:
    0.999
  features.models.9.conv.models.0.dsOp.multiclass.0.weight:
    0.99
  features.models.9.conv.models.0.dsOp.binary.0.weight:
    0.999
  features.models.9.conv.models.3.weight:
    0.99
  features.models.9.conv.models.3.taskOp.multiclass.weight:
    0.99
  features.models.9.conv.models.3.taskOp.binary.weight:
    0.999
  features.models.9.conv.models.6.weight:
    0.99
  features.models.9.conv.models.6.taskOp.multiclass.weight:
    0.99
  features.models.9.conv.models.6.taskOp.binary.weight:
    0.999
  features.models.9.conv.models.6.dsOp.multiclass.0.weight:
    0.99
  features.models.9.conv.models.6.dsOp.binary.0.weight:
    0.999
  features.models.10.conv.models.0.weight:
    0.99
  features.models.10.conv.models.0.taskOp.multiclass.weight:
    0.99
  features.models.10.conv.models.0.taskOp.binary.weight:
    0.999
  features.models.10.conv.models.0.dsOp.multiclass.0.weight:
    0.99
  features.models.10.conv.models.0.dsOp.binary.0.weight:
    0.999
  features.models.10.conv.models.3.weight:
    0.99
  features.models.10.conv.models.3.taskOp.multiclass.weight:
    0.99
  features.models.10.conv.models.3.taskOp.binary.weight:
    0.999
  features.models.10.conv.models.6.weight:
    0.99
  features.models.10.conv.models.6.taskOp.multiclass.weight:
    0.99
  features.models.10.conv.models.6.taskOp.binary.weight:
    0.999
  features.models.10.conv.models.6.dsOp.multiclass.0.weight:
    0.99
  features.models.10.conv.models.6.dsOp.binary.0.weight:
    0.999
  features.models.11.conv.models.0.weight:
    0.99
  features.models.11.conv.models.0.taskOp.multiclass.weight:
    0.99
  features.models.11.conv.models.0.taskOp.binary.weight:
    0.999
  features.models.11.conv.models.0.dsOp.multiclass.0.weight:
    0.99
  features.models.11.conv.models.0.dsOp.binary.0.weight:
    0.999
  features.models.11.conv.models.3.weight:
    0.99
  features.models.11.conv.models.3.taskOp.multiclass.weight:
    0.99
  features.models.11.conv.models.3.taskOp.binary.weight:
    0.999
  features.models.11.conv.models.6.weight:
    0.99
  features.models.11.conv.models.6.taskOp.multiclass.weight:
    0.99
  features.models.11.conv.models.6.taskOp.binary.weight:
    0.999
  features.models.11.conv.models.6.dsOp.multiclass.0.weight:
    0.99
  features.models.11.conv.models.6.dsOp.binary.0.weight:
    0.999
  features.models.12.conv.models.0.weight:
    0.99
  features.models.12.conv.models.0.taskOp.multiclass.weight:
    0.99
  features.models.12.conv.models.0.taskOp.binary.weight:
    0.999
  features.models.12.conv.models.0.dsOp.multiclass.0.weight:
    0.99
  features.models.12.conv.models.0.dsOp.binary.0.weight:
    0.999
  features.models.12.conv.models.3.weight:
    0.99
  features.models.12.conv.models.3.taskOp.multiclass.weight:
    0.99
  features.models.12.conv.models.3.taskOp.binary.weight:
    0.999
  features.models.12.conv.models.6.weight:
    0.99
  features.models.12.conv.models.6.taskOp.multiclass.weight:
    0.99
  features.models.12.conv.models.6.taskOp.binary.weight:
    0.999
  features.models.12.conv.models.6.dsOp.multiclass.0.weight:
    0.99
  features.models.12.conv.models.6.dsOp.binary.0.weight:
    0.999
  features.models.13.conv.models.0.weight:
    0.99
  features.models.13.conv.models.0.taskOp.multiclass.weight:
    0.99
  features.models.13.conv.models.0.taskOp.binary.weight:
    0.999
  features.models.13.conv.models.0.dsOp.multiclass.0.weight:
    0.99
  features.models.13.conv.models.0.dsOp.binary.0.weight:
    0.999
  features.models.13.conv.models.3.weight:
    0.99
  features.models.13.conv.models.3.taskOp.multiclass.weight:
    0.99
  features.models.13.conv.models.3.taskOp.binary.weight:
    0.999
  features.models.13.conv.models.6.weight:
    0.99
  features.models.13.conv.models.6.taskOp.multiclass.weight:
    0.99
  features.models.13.conv.models.6.taskOp.binary.weight:
    0.999
  features.models.13.conv.models.6.dsOp.multiclass.0.weight:
    0.99
  features.models.13.conv.models.6.dsOp.binary.0.weight:
    0.999
  features.models.14.conv.models.0.weight:
    0.99
  features.models.14.conv.models.0.taskOp.multiclass.weight:
    0.99
  features.models.14.conv.models.0.taskOp.binary.weight:
    0.999
  features.models.14.conv.models.0.dsOp.multiclass.0.weight:
    0.99
  features.models.14.conv.models.0.dsOp.binary.0.weight:
    0.999
  features.models.14.conv.models.3.weight:
    0.99
  features.models.14.conv.models.3.taskOp.multiclass.weight:
    0.99
  features.models.14.conv.models.3.taskOp.binary.weight:
    0.999
  features.models.14.conv.models.3.dsOp.multiclass.0.weight:
    0.99
  features.models.14.conv.models.3.dsOp.binary.0.weight:
    0.999
  features.models.14.conv.models.6.weight:
    0.99
  features.models.14.conv.models.6.taskOp.multiclass.weight:
    0.99
  features.models.14.conv.models.6.taskOp.binary.weight:
    0.999
  features.models.14.conv.models.6.dsOp.multiclass.0.weight:
    0.99
  features.models.14.conv.models.6.dsOp.binary.0.weight:
    0.999
  features.models.15.conv.models.0.weight:
    0.99
  features.models.15.conv.models.0.taskOp.multiclass.weight:
    0.99
  features.models.15.conv.models.0.taskOp.binary.weight:
    0.999
  features.models.15.conv.models.0.dsOp.multiclass.0.weight:
    0.99
  features.models.15.conv.models.0.dsOp.binary.0.weight:
    0.999
  features.models.15.conv.models.3.weight:
    0.99
  features.models.15.conv.models.3.taskOp.multiclass.weight:
    0.99
  features.models.15.conv.models.3.taskOp.binary.weight:
    0.999
  features.models.15.conv.models.6.weight:
    0.99
  features.models.15.conv.models.6.taskOp.multiclass.weight:
    0.99
  features.models.15.conv.models.6.taskOp.binary.weight:
    0.999
  features.models.15.conv.models.6.dsOp.multiclass.0.weight:
    0.99
  features.models.15.conv.models.6.dsOp.binary.0.weight:
    0.999
  features.models.16.conv.models.0.weight:
    0.99
  features.models.16.conv.models.0.taskOp.multiclass.weight:
    0.99
  features.models.16.conv.models.0.taskOp.binary.weight:
    0.999
  features.models.16.conv.models.0.dsOp.multiclass.0.weight:
    0.99
  features.models.16.conv.models.0.dsOp.binary.0.weight:
    0.999
  features.models.16.conv.models.3.weight:
    0.99
  features.models.16.conv.models.3.taskOp.multiclass.weight:
    0.99
  features.models.16.conv.models.3.taskOp.binary.weight:
    0.999
  features.models.16.conv.models.6.weight:
    0.99
  features.models.16.conv.models.6.taskOp.multiclass.weight:
    0.99
  features.models.16.conv.models.6.taskOp.binary.weight:
    0.999
  features.models.16.conv.models.6.dsOp.multiclass.0.weight:
    0.99
  features.models.16.conv.models.6.dsOp.binary.0.weight:
    0.999
  features.models.17.conv.models.0.weight:
    0.99
  features.models.17.conv.models.0.taskOp.multiclass.weight:
    0.99
  features.models.17.conv.models.0.taskOp.binary.weight:
    0.999
  features.models.17.conv.models.0.dsOp.multiclass.0.weight:
    0.99
  features.models.17.conv.models.0.dsOp.binary.0.weight:
    0.999
  features.models.17.conv.models.3.weight:
    0.99
  features.models.17.conv.models.3.taskOp.multiclass.weight:
    0.99
  features.models.17.conv.models.3.taskOp.binary.weight:
    0.999
  features.models.17.conv.models.6.weight:
    0.99
  features.models.17.conv.models.6.taskOp.multiclass.weight:
    0.99
  features.models.17.conv.models.6.taskOp.binary.weight:
    0.999
  features.models.17.conv.models.6.dsOp.multiclass.0.weight:
    0.99
  features.models.17.conv.models.6.dsOp.binary.0.weight:
    0.999
  features.models.18.models.0.weight:
    0.99
  features.models.18.models.0.taskOp.multiclass.weight:
    0.99
  features.models.18.models.0.taskOp.binary.weight:
    0.999
  features.models.18.models.0.dsOp.multiclass.0.weight:
    0.99
  features.models.18.models.0.dsOp.binary.0.weight:
    0.999